# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170512_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='catgories',
            new_name='categories',
        ),
    ]
